name: Publish

on:
  release:
    types: [published]

jobs:
  push:
    name: Publish to Rubygems
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3

      - uses: rubygems/release-gem@v1
